version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-"postgres"}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-"Cypher@001"}
      POSTGRES_DB: ${POSTGRES_DB:-"personalized_coach"}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-personalized_coach}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fitness_api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Cypher%40001@postgres:5432/personalized_coach
      # AWS credentials for DVC
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      
      # HuggingFace
      HF_TOKEN: ${HF_TOKEN}
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
      
    

volumes:
  postgres_data:
